<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Emcore.UserOrganization.Domain\Emcore.UserOrganization.Domain.csproj" />
    <ProjectReference Include="..\..\src\Emcore.UserOrganization.Application\Emcore.UserOrganization.Application.csproj" />
    <ProjectReference Include="..\..\src\Emcore.UserOrganization.Infrastructure\Emcore.UserOrganization.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Emcore.UserOrganization.Contracts\Emcore.UserOrganization.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Emcore.UserOrganization.Api\Emcore.UserOrganization.Api.csproj" />
    <ProjectReference Include="..\..\src\Emcore.UserOrganization.Worker\Emcore.UserOrganization.Worker.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NetArchTest.Rules" />
  </ItemGroup>
</Project>