CREATE TABLE dbo.USER_ACCOUNT (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    UlidId VARCHAR(26) NOT NULL,
    Status VARCHAR(50) NOT NULL DEFAULT 'PendingVerification',
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    RowVersion ROWVERSION
);

CREATE TABLE dbo.USER_CREDENTIAL (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL,
    HashAlgorithm VARCHAR(50) NOT NULL DEFAULT 'PBKDF2',
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    RowVersion ROWVERSION
);

CREATE TABLE dbo.USER_EMAIL (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    EmailAddress VARCHAR(255) NOT NULL,
    NormalizedEmail VARCHAR(255) NOT NULL,
    IsVerified BIT NOT NULL DEFAULT 0,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    RowVersion ROWVERSION
);

CREATE TABLE dbo.USER_MOBILE (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    MobileNumber VARCHAR(50) NOT NULL,
    NormalizedMobile VARCHAR(50) NOT NULL,
    IsVerified BIT NOT NULL DEFAULT 0,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    RowVersion ROWVERSION
);

CREATE TABLE dbo.SERVICE_CLIENT (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    ClientId VARCHAR(255) NOT NULL,
    ClientSecretHash VARCHAR(255) NOT NULL,
    Status VARCHAR(50) NOT NULL DEFAULT 'Active',
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    RowVersion ROWVERSION
);
GO
