CREATE TABLE dbo.ACCOUNT_VERIFICATION (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    TokenHash VARCHAR(255) NOT NULL,
    Channel VARCHAR(50) NOT NULL DEFAULT 'Email',
    Status VARCHAR(50) NOT NULL DEFAULT 'Issued',
    AttemptCount INT NOT NULL DEFAULT 0,
    ExpiresAtUtc DATETIME2 NOT NULL,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    RowVersion ROWVERSION
);

CREATE TABLE dbo.ACCOUNT_RECOVERY (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    TokenHash VARCHAR(255) NOT NULL,
    Status VARCHAR(50) NOT NULL DEFAULT 'Created',
    AttemptCount INT NOT NULL DEFAULT 0,
    ExpiresAtUtc DATETIME2 NOT NULL,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    RowVersion ROWVERSION
);
GO
