CREATE TABLE dbo.USER_SESSION (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    Status VARCHAR(50) NOT NULL DEFAULT 'Active',
    TokenFamilyId VARCHAR(100) NULL,
    DeviceLabel VARCHAR(255) NULL,
    IpAddress VARCHAR(50) NULL,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    LastActivityAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    RevokedAtUtc DATETIME2 NULL,
    RowVersion ROWVERSION
);

CREATE TABLE dbo.REFRESH_TOKEN (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    SessionId UNIQUEIDENTIFIER NOT NULL,
    TokenHash VARCHAR(255) NOT NULL,
    FamilyId VARCHAR(100) NOT NULL,
    ExpiresAtUtc DATETIME2 NOT NULL,
    IsRevoked BIT NOT NULL DEFAULT 0,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    RevokedAtUtc DATETIME2 NULL,
    ReplacedByTokenHash VARCHAR(255) NULL,
    RowVersion ROWVERSION
);

CREATE TABLE dbo.LOGIN_ATTEMPT (
    UserId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    FailedCount INT NOT NULL DEFAULT 0,
    LockoutEndUtc DATETIME2 NULL,
    UpdatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    RowVersion ROWVERSION
);

CREATE TABLE dbo.PASSWORD_HISTORY (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    RowVersion ROWVERSION
);
GO
