CREATE TABLE dbo.USER_SESSION (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    SessionToken VARCHAR(255) NOT NULL,
    ExpiresAtUtc DATETIME2 NOT NULL,
    IsRevoked BIT NOT NULL,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    RowVersion ROWVERSION
);

CREATE TABLE dbo.REFRESH_TOKEN (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    SessionId UNIQUEIDENTIFIER NOT NULL,
    Token VARCHAR(255) NOT NULL,
    ExpiresAtUtc DATETIME2 NOT NULL,
    IsRevoked BIT NOT NULL,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    RowVersion ROWVERSION
);

CREATE TABLE dbo.LOGIN_ATTEMPT (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    IsSuccess BIT NOT NULL,
    AttemptedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    RowVersion ROWVERSION
);

CREATE TABLE dbo.PASSWORD_HISTORY (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    RowVersion ROWVERSION
);
GO
