CREATE TABLE dbo.IDENTITY_OUTBOX (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    MessageType VARCHAR(255) NOT NULL,
    SchemaVersion VARCHAR(50) NOT NULL DEFAULT '1.0.0',
    Payload NVARCHAR(MAX) NOT NULL,
    IsPublished BIT NOT NULL DEFAULT 0,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    PublishedAtUtc DATETIME2 NULL,
    AttemptCount INT NOT NULL DEFAULT 0,
    LastError NVARCHAR(MAX) NULL,
    CorrelationId VARCHAR(100) NULL,
    TraceId VARCHAR(100) NULL,
    RowVersion ROWVERSION
);

CREATE TABLE dbo.IDENTITY_INBOX (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    MessageId UNIQUEIDENTIFIER NOT NULL,
    ProcessedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    RowVersion ROWVERSION
);

CREATE TABLE dbo.IDEMPOTENCY_REQUEST (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    IdempotencyKey VARCHAR(255) NOT NULL,
    Name VARCHAR(255) NOT NULL,
    RequestHash VARCHAR(255) NOT NULL DEFAULT '',
    StatusCode INT NULL,
    ResponseBody NVARCHAR(MAX) NULL,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    RowVersion ROWVERSION
);
GO
