CREATE UNIQUE INDEX IX_USER_ACCOUNT_UlidId ON dbo.USER_ACCOUNT (UlidId);
CREATE UNIQUE INDEX IX_USER_EMAIL_NormalizedEmail ON dbo.USER_EMAIL (NormalizedEmail) WHERE NormalizedEmail <> '';
CREATE UNIQUE INDEX IX_USER_MOBILE_NormalizedMobile ON dbo.USER_MOBILE (NormalizedMobile) WHERE NormalizedMobile <> '';
CREATE UNIQUE INDEX IX_IDEMPOTENCY_REQUEST_Key ON dbo.IDEMPOTENCY_REQUEST (IdempotencyKey);

CREATE INDEX IX_USER_EMAIL_UserId ON dbo.USER_EMAIL (UserId);
CREATE INDEX IX_USER_MOBILE_UserId ON dbo.USER_MOBILE (UserId);
CREATE INDEX IX_USER_CREDENTIAL_UserId ON dbo.USER_CREDENTIAL (UserId);
CREATE INDEX IX_ACCOUNT_VERIFICATION_UserId_Status ON dbo.ACCOUNT_VERIFICATION (UserId, Status);
CREATE INDEX IX_ACCOUNT_RECOVERY_UserId_Status ON dbo.ACCOUNT_RECOVERY (UserId, Status);
CREATE INDEX IX_USER_SESSION_UserId_Status ON dbo.USER_SESSION (UserId, Status);
CREATE INDEX IX_REFRESH_TOKEN_SessionId_TokenHash ON dbo.REFRESH_TOKEN (SessionId, TokenHash);
CREATE INDEX IX_IDENTITY_OUTBOX_IsPublished_CreatedAt ON dbo.IDENTITY_OUTBOX (IsPublished, CreatedAtUtc);
GO
