CREATE UNIQUE INDEX IX_USER_ACCOUNT_UlidId ON dbo.USER_ACCOUNT (UlidId);
CREATE UNIQUE INDEX IX_USER_EMAIL_EmailAddress ON dbo.USER_EMAIL (EmailAddress);
CREATE UNIQUE INDEX IX_IDEMPOTENCY_REQUEST_Key ON dbo.IDEMPOTENCY_REQUEST (IdempotencyKey);
GO
