CREATE PROCEDURE dbo.PR_IDENTITY_REGISTER_USER AS BEGIN SET NOCOUNT ON; END;
GO
CREATE PROCEDURE dbo.PR_IDENTITY_CREATE_VERIFICATION AS BEGIN SET NOCOUNT ON; END;
GO
CREATE PROCEDURE dbo.PR_IDENTITY_VERIFY_ACCOUNT AS BEGIN SET NOCOUNT ON; END;
GO
CREATE PROCEDURE dbo.PR_IDENTITY_RESEND_VERIFICATION AS BEGIN SET NOCOUNT ON; END;
GO
CREATE PROCEDURE dbo.PR_IDENTITY_GET_LOGIN_CONTEXT AS BEGIN SET NOCOUNT ON; END;
GO
CREATE PROCEDURE dbo.PR_IDENTITY_RECORD_LOGIN_ATTEMPT AS BEGIN SET NOCOUNT ON; END;
GO
CREATE PROCEDURE dbo.PR_IDENTITY_APPLY_LOGIN_FAILURE AS BEGIN SET NOCOUNT ON; END;
GO
CREATE PROCEDURE dbo.PR_IDENTITY_CLEAR_LOGIN_FAILURE AS BEGIN SET NOCOUNT ON; END;
GO
CREATE PROCEDURE dbo.PR_IDENTITY_CREATE_SESSION AS BEGIN SET NOCOUNT ON; END;
GO
CREATE PROCEDURE dbo.PR_IDENTITY_ROTATE_REFRESH_TOKEN AS BEGIN SET NOCOUNT ON; END;
GO
CREATE PROCEDURE dbo.PR_IDENTITY_REVOKE_SESSION AS BEGIN SET NOCOUNT ON; END;
GO
CREATE PROCEDURE dbo.PR_IDENTITY_REVOKE_ALL_SESSIONS AS BEGIN SET NOCOUNT ON; END;
GO
CREATE PROCEDURE dbo.PR_IDENTITY_LIST_SESSIONS AS BEGIN SET NOCOUNT ON; END;
GO
CREATE PROCEDURE dbo.PR_IDENTITY_CREATE_RECOVERY_REQUEST AS BEGIN SET NOCOUNT ON; END;
GO
CREATE PROCEDURE dbo.PR_IDENTITY_RESET_PASSWORD AS BEGIN SET NOCOUNT ON; END;
GO
CREATE PROCEDURE dbo.PR_IDENTITY_GET_PENDING_OUTBOX AS BEGIN SET NOCOUNT ON; END;
GO
CREATE PROCEDURE dbo.PR_IDENTITY_MARK_OUTBOX_PUBLISHED AS BEGIN SET NOCOUNT ON; END;
GO
CREATE PROCEDURE dbo.PR_IDENTITY_MARK_OUTBOX_FAILED AS BEGIN SET NOCOUNT ON; END;
GO
CREATE PROCEDURE dbo.PR_IDENTITY_TRY_RECORD_INBOX AS BEGIN SET NOCOUNT ON; END;
GO
CREATE PROCEDURE dbo.PR_IDENTITY_BEGIN_IDEMPOTENT_REQUEST AS BEGIN SET NOCOUNT ON; END;
GO
CREATE PROCEDURE dbo.PR_IDENTITY_COMPLETE_IDEMPOTENT_REQUEST AS BEGIN SET NOCOUNT ON; END;
GO
CREATE PROCEDURE dbo.PR_IDENTITY_GET_IDEMPOTENT_RESULT AS BEGIN SET NOCOUNT ON; END;
GO
