<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Emcore.InspectionTrust.Domain\Emcore.InspectionTrust.Domain.csproj" />
    <ProjectReference Include="..\Emcore.InspectionTrust.Application\Emcore.InspectionTrust.Application.csproj" />
    <ProjectReference Include="..\..\..\..\building-blocks\Emcore.BuildingBlocks.Data\Emcore.BuildingBlocks.Data.csproj" />
    <ProjectReference Include="..\..\..\..\building-blocks\Emcore.BuildingBlocks.Messaging\Emcore.BuildingBlocks.Messaging.csproj" />
    <ProjectReference Include="..\..\..\..\building-blocks\Emcore.BuildingBlocks.Caching\Emcore.BuildingBlocks.Caching.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
  </ItemGroup>
</Project>