CREATE TABLE dbo.ORGANIZATION (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    EntityType INT NOT NULL,
    DisplayName VARCHAR(255) NOT NULL,
    LegalName VARCHAR(255) NULL,
    Status INT NOT NULL,
    OwnerUserId UNIQUEIDENTIFIER NOT NULL,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAtUtc DATETIME2 NULL,
    RowVersion ROWVERSION
);

CREATE TABLE dbo.ORGANIZATION_CAPABILITY (
    OrganizationId UNIQUEIDENTIFIER NOT NULL,
    CapabilityCode INT NOT NULL,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_ORGANIZATION_CAPABILITY PRIMARY KEY (OrganizationId, CapabilityCode),
    CONSTRAINT FK_ORGANIZATION_CAPABILITY_ORG FOREIGN KEY (OrganizationId) REFERENCES dbo.ORGANIZATION (Id) ON DELETE CASCADE
);
GO
