<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Emcore.SubscriptionPayment.Domain\Emcore.SubscriptionPayment.Domain.csproj" />
    <ProjectReference Include="..\..\src\Emcore.SubscriptionPayment.Application\Emcore.SubscriptionPayment.Application.csproj" />
    <ProjectReference Include="..\..\src\Emcore.SubscriptionPayment.Infrastructure\Emcore.SubscriptionPayment.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Emcore.SubscriptionPayment.Contracts\Emcore.SubscriptionPayment.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Emcore.SubscriptionPayment.Api\Emcore.SubscriptionPayment.Api.csproj" />
    <ProjectReference Include="..\..\src\Emcore.SubscriptionPayment.Worker\Emcore.SubscriptionPayment.Worker.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NetArchTest.Rules" />
  </ItemGroup>
</Project>