name: Manual Container Build
on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Service to build'
        required: true
        type: string
      tag:
        description: 'Image tag'
        required: true
        type: string
      push:
        description: 'Push image'
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker Image
      run: docker build -t ${{ inputs.service }}:${{ inputs.tag }} -f services/${{ inputs.service }}/Dockerfile.Api .
